spring:
  datasource:
    url: jdbc:mysql://localhost:3307/sample
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    hiddenmethod:
      filter:
        enabled: true

server:
  port: 50000